version: '3.8'

services:
  sidewinder:
    build: .
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./tests/output:/app/tests/output
    environment:
      - SPARK_LOCAL_IP=sidewinder
      - SPARK_MASTER_HOST=sidewinder
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "4040:4040"  # Spark UI
    networks:
      - sidewinder_net

networks:
  sidewinder_net:
    driver: bridge 